<header>
	<div class="header-container">
		<div id="top-header">
			<div class="grid-33 tablet-grid-33 mobile-grid-20">
				<div class="header-left">
					<ul class="hide-on-mobile">
						<li><a href="#" target="_blank"><i class="fa fa-facebook fa-lg" aria-hidden="true"></i><span class="hidden">Facebook</span></a></li>
						<li><a href="#" target="_blank"><i class="fa fa-instagram fa-lg" aria-hidden="true"></i><span class="hidden">Instagram</span></a></li>
						<li><a href="#" target="_blank"><i class="fa fa-twitter fa-lg" aria-hidden="true"></i><span class="hidden">Twitter</span></a></li>
						<li><a href="#" target="_blank"><i class="fa fa-pinterest fa-lg" aria-hidden="true"></i><span class="hidden">Pinterest</span></a></li>
						<li><a href="/contact-us.inc"><i class="fa fa-phone fa-lg" aria-hidden="true"></i> 888.888.8888</a></li>
					</ul>
					<div class="hide-on-tablet hide-on-desktop">
						<a class="slideout-menu-toggle" href="javascript:void(0)"><i class="fa fa-bars fa-lg" aria-hidden="true"></i><span class="hidden">Menu</span></a>
					</div>
				</div>
			</div>

			<div class="grid-33 tablet-grid-33 mobile-grid-60">
				<div id="logo">
					<a href="/"><img src="images/logo.png" width="325" height="36" alt="M.D. Home Furnishings" /></a>
				</div>
			</div>

			<div class="grid-33 tablet-grid-33 mobile-grid-20">
				<div class="header-right">
					<ul>
						<li>
							<a href="javascript:void(0)" class="opensearch"><i class="fa fa-search fa-lg" aria-hidden="true"></i><span class="hidden">Search</span></a>
						</li>
						<li class="hide-on-mobile">
							<a href="/viewcart.aspx" rel="noindex,nofollow"><i class="fa fa-shopping-cart fa-lg" aria-hidden="true"></i><span class="hidden">Cart</span> (<viewCartQuantitySummary></viewCartQuantitySummary>)</a>
						</li>
						<li class="hide-on-mobile">
							<a style="border: 0" href="javascript:void(0)"><i class="fa fa-user-o fa-lg" aria-hidden="true"></i><span class="hidden">Account</span></a>
							<ul>
								<li id="login"><a href="/login.aspx" rel="noindex,nofollow">Login</a></li>
								<li id="viewAccountLink" style="display: none;"><a href="/modifyaccount.aspx" rel="noindex,nofollow">View Account</a></li>
								<li id="logoutLink" style="display: none;"><a href="/homepage.aspx?logout=true" rel="noindex,nofollow">Logout</a></li>
								<li id="registerlink"><a href="/createaccount.aspx" rel="noindex,nofollow">Register</a></li>
								<li><a href="/favorites.aspx" rel="noindex,nofollow">Favorites</a></li>
							</ul>
						</li>
					</ul>
				</div>
				<div class="clear"></div>
			</div>
			<div class="clear"></div>
		</div>

		<div id="sticky-header">
			<nav class="hide-on-mobile">
				<ul>
					<li><a href="javascript:void(0)">Shop</a>
						<ul id="room-submenu">
							<li><a href="/living-room.inc">Living Room <i class="fa fa-angle-right" aria-hidden="true"></i></a>
								<AttributeList id="LivingRoom" class="shopbycolor" ListAttribute="Type" FilterAttribute="Room"  FilterAttributeValue="Living Room" ItemType="item"></AttributeList>
							</li>
							<li><a href="/dining-room.inc">Dining Room <i class="fa fa-angle-right" aria-hidden="true"></i></a>
								<AttributeList id="DiningRoom" class="shopbycolor" ListAttribute="Type" FilterAttribute="Room"  FilterAttributeValue="Dining Room" ItemType="item"></AttributeList>
							</li>
							<li><a href="/bedroom.inc">Bedroom <i class="fa fa-angle-right" aria-hidden="true"></i></a>
								<AttributeList id="Bedroom" class="shopbycolor" ListAttribute="Type" FilterAttribute="Room" FilterAttributeValue="Bedroom" ItemType="item"></AttributeList>
							</li>
							<li><a href="/home-office.inc">Home Office <i class="fa fa-angle-right" aria-hidden="true"></i></a>
								<AttributeList id="HomeOffice" class="shopbycolor" ListAttribute="Type" FilterAttribute="Department" FilterAttributeValue="Home Office" ItemType="item"></AttributeList>
							</li>
							<li><a href="/entertainment.inc">Entertainment <i class="fa fa-angle-right" aria-hidden="true"></i></a>
								<AttributeList id="HomeEntertainment" class="shopbycolor" ListAttribute="Type" FilterAttribute="Department" FilterAttributeValue="Home Entertainment" ItemType="item"></AttributeList>
							</li>
							<li><a href="/accessories.inc">Accessories <i class="fa fa-angle-right" aria-hidden="true"></i></a>
								<AttributeList id="Accessories" class="shopbycolor" ListAttribute="Type" FilterAttribute="Department" FilterAttributeValue="Accessories" ItemType="item"></AttributeList>
							</li>
							<li><a href="/mattresses/">Mattresses</a></li>
						</ul>
					</li>
					<li><a href="javascript:void(0)">Design</a>
						<ul>
							<li><a href="/design-center.inc">Design Center</a></li>
							<li><a href="/room-planner.inc">Room Planner</a></li>
							<li><a href="javascript:void(0)">Find a Designer</a></li>
						</ul>
					</li>
					<li><a href="javascript:void(0)">Learn</a>
						<ul>
							<li><a href="/about-us.inc">Our Story</a></li>
							<li><a href="/brands.inc">Brands We Carry</a></li>
						</ul>
					</li>
					<li><a href="javascript:void(0)">Specials</a>
						<ul>
							<li><a href="/trending-wall/">Trending Wall</a></li>
							<li><a href="/displayflyer.aspx">Special Events</a></li>
							<li><a href="/all/department-type.aspx?sku-status=clearance">Clearance</a></li>
						</ul>
					</li>
					<li><a href="javascript:void(0)">Financing</a></li>
					<li><a href="javascript:void(0)">Contact</a>
						<ul>
							<li><a href="/contact-us.inc">Hours & Directions</a></li>
							<li><a href="/contact-us.inc">Contact Us</a></li>
							<li><a href="/join-email.inc">Newsletter</a></li>
						</ul>
					</li>
				</ul>
				<div class="clear"></div>
			</nav>
			<div id="search-bar">
				<div id="searchbox">
					<div id="search-left">
						<div id="loggedinas" style="display: none; visibility: hidden"></div>
						<label class="hidden" for="SearchValue">Search Keyword</label>
						<input type="text" id="SearchValue" name="SearchValue" onkeypress="submitsearch(event);" value="" />
					</div>
					<div id="search-right">
						<label class="hidden" for="searchbutton">Search</label>
						<input onClick="goSearch();" name="searchbutton" id="searchbutton" type="Submit" value="Go" />
					</div>
					<div id="search-close">
						<a href="javascript:void(0)" class="opensearch"><i class="fa fa-times" aria-hidden="true"></i><span class="hidden">Close Search</span></a>
					</div>
					<div class="clear"></div>
				</div>
			</div>
		</div>

	</div>
</header>

<div class="slideout-menu">
	<div>
		<p>Menu</p>
		<p><a href="tel:+1-888-888-8888"><i class="fa fa-phone fa-lg" aria-hidden="true"></i><span class="hidden">Phone</span></a></p>
		<p><a href="https://www.google.com/maps" target="_blank"><i class="fa fa-map-marker fa-lg" aria-hidden="true"></i><span class="hidden">Location</span></a></p>
		<span class="slideout-menu-toggle">x</span>
	</div>
	<ul>
		<li><a href="/viewcart.aspx" rel="noindex,nofollow">Cart (<span class="cart-qty"></span>)<i class="fa fa-shopping-cart fa-lg" aria-hidden="true"></i></a></li>
		<li class="slide-in"><a href="javascript:void(0)">Shop <i class="fa fa-angle-double-right" aria-hidden="true"></i></a>
			<ul style="display: none;">
				<li><a href="/living-room.inc">Living Room <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
				<li><a href="/dining-room.inc">Dining Room <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
				<li><a href="/bedroom.inc">Bedroom <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
				<li><a href="/home-office.inc">Home Office <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
				<li><a href="/entertainment.inc">Entertainment <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
				<li><a href="/accessories.inc">Accessories <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
				<li><a href="/mattresses/">Mattresses <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
			</ul>
		</li>
		<li class="spacer">&nbsp;</li>
		<li class="expandable"><a href="javascript:void(0)">Design</a>
			<ul style="display: none;">
				<li><a href="/design-center.inc">Design Center <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
				<li><a href="/room-planner.inc">Room Planner <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
				<li><a href="javascript:void(0)">Find a Designer <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
			</ul>
		</li>
		<li class="expandable"><a href="javascript:void(0)">Learn</a>
			<ul style="display: none;">
				<li><a href="/about-us.inc">Our Story <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
				<li><a href="/brands.inc">Brands We Carry <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
			</ul>
		</li>
		<li class="expandable"><a href="javascript:void(0)">Specials</a>
			<ul style="display: none;">
				<li><a href="/trending-wall/">Trending Wall <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
				<li><a href="/displayflyer.aspx">Special Events <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
				<li><a href="/all/department-type.aspx?sku-status=clearance">Clearance <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
			</ul>
		</li>
		<li class="spacer">&nbsp;</li>
		<li><a href="javascript:void(0)">Financing <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
		<li><a href="/join-email.inc">Newsletter <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
		<li><a href="/contact-us.inc">Contact Us <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
		<li class="spacer">&nbsp;</li>
		<li class="expandable"><a href="javascript:void(0)">Account</a>
			<ul style="display: none;">
				<li id="login2"><a href="/login.aspx" rel="noindex,nofollow">Login <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
				<li id="viewAccountLink2" style="display: none;"><a href="/modifyaccount.aspx" rel="noindex,nofollow">View Account <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
				<li id="logoutLink2" style="display: none;"><a href="homepage.aspx?logout=true" rel="noindex,nofollow">Logout <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
				<li id="registerlink2"><a href="/createaccount.aspx" rel="noindex,nofollow">Register <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
				<li><a href="/favorites.aspx" rel="noindex,nofollow">Favorites <i class="fa fa-angle-right" aria-hidden="true"></i></a></li>
			</ul>
		</li>
	</ul>
</div>